#!/usr/bin/with-contenv bash

if [ "${#CF_TUNNEL_SIMPLE_TOKEN}" -gt 0 ]; then
    exec cloudflared service install ${CF_TUNNEL_SIMPLE_TOKEN}
else
    exec s6-setuidgid abc cloudflared tunnel --no-autoupdate --config /etc/cloudflared/config.yml run
fi